### ISSUE TITLE
Week 2: Advanced UI Features

### ISSUE THREAD

**Issue by rayaboutany** [rayaboutany/Euchre#22]
Task:
- Add sound effects using the Godot engine's audio capabilities.

Responsibilities:
- Integrate animations/transitions for visual effects.

**Comment by riverboop** [comment]
haven't gotten around to doing this, was working with erin on adding timer code to card playing, will add animations after that's complete. in the meantime made the table ui better and fixed the trump suit picking so it gets the correct suit. will lock in for week 3 so we can finalize the project

**Comment by riverboop** [comment]
card playing animations fully implemented
